{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "89f51f1a-55c6-4a37-ac99-7c50c5f4caea",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Name: pytube\n",
      "Version: 15.0.0\n",
      "Summary: Python 3 library for downloading YouTube Videos.\n",
      "Home-page: https://github.com/pytube/pytube\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1672, in print\n",
      "    with self:\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 864, in __exit__\n",
      "    self._exit_buffer()\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 822, in _exit_buffer\n",
      "    self._check_buffer()\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 2027, in _check_buffer\n",
      "    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\_windows_renderer.py\", line 19, in legacy_windows_render\n",
      "    term.write_text(text)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\_win32_console.py\", line 403, in write_text\n",
      "    self.write(text)\n",
      "UnicodeEncodeError: 'gbk' codec can't encode character '\\xa0' in position 14: illegal multibyte sequence\n",
      "Call stack:\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\pip.exe\\__main__.py\", line 7, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 79, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 234, in _main\n",
      "    return run(options, args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 180, in exc_logging_wrapper\n",
      "    status = run_func(*args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 45, in run\n",
      "    if not print_results(\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 159, in print_results\n",
      "    write_output(\"Author: %s\", dist.author)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\utils\\misc.py\", line 387, in write_output\n",
      "    logger.info(msg, *args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1477, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1624, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1634, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1696, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 968, in handle\n",
      "    self.emit(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Author: %s'\n",
      "Arguments: ('Ronnie\\xa0Ghose, Taylor Fox Dahlin, Nick Ficano',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1672, in print\n",
      "    with self:\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 864, in __exit__\n",
      "    self._exit_buffer()\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 822, in _exit_buffer\n",
      "    self._check_buffer()\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 2027, in _check_buffer\n",
      "    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\_windows_renderer.py\", line 19, in legacy_windows_render\n",
      "    term.write_text(text)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\_win32_console.py\", line 403, in write_text\n",
      "    self.write(text)\n",
      "UnicodeEncodeError: 'gbk' codec can't encode character '\\xa0' in position 14: illegal multibyte sequence\n",
      "Call stack:\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\pip.exe\\__main__.py\", line 7, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 79, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 234, in _main\n",
      "    return run(options, args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 180, in exc_logging_wrapper\n",
      "    status = run_func(*args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 45, in run\n",
      "    if not print_results(\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 160, in print_results\n",
      "    write_output(\"Author-email: %s\", dist.author_email)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\utils\\misc.py\", line 387, in write_output\n",
      "    logger.info(msg, *args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1477, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1624, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1634, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1696, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 968, in handle\n",
      "    self.emit(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Author-email: %s'\n",
      "Arguments: ('hey@pytube.io',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1672, in print\n",
      "    with self:\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 864, in __exit__\n",
      "    self._exit_buffer()\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 822, in _exit_buffer\n",
      "    self._check_buffer()\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 2027, in _check_buffer\n",
      "    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\_windows_renderer.py\", line 19, in legacy_windows_render\n",
      "    term.write_text(text)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\_win32_console.py\", line 403, in write_text\n",
      "    self.write(text)\n",
      "UnicodeEncodeError: 'gbk' codec can't encode character '\\xa0' in position 14: illegal multibyte sequence\n",
      "Call stack:\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\pip.exe\\__main__.py\", line 7, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 79, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 234, in _main\n",
      "    return run(options, args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 180, in exc_logging_wrapper\n",
      "    status = run_func(*args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 45, in run\n",
      "    if not print_results(\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 161, in print_results\n",
      "    write_output(\"License: %s\", dist.license)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\utils\\misc.py\", line 387, in write_output\n",
      "    logger.info(msg, *args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1477, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1624, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1634, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1696, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 968, in handle\n",
      "    self.emit(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'License: %s'\n",
      "Arguments: ('The Unlicense (Unlicense)',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1672, in print\n",
      "    with self:\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 864, in __exit__\n",
      "    self._exit_buffer()\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 822, in _exit_buffer\n",
      "    self._check_buffer()\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 2027, in _check_buffer\n",
      "    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\_windows_renderer.py\", line 19, in legacy_windows_render\n",
      "    term.write_text(text)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\_win32_console.py\", line 403, in write_text\n",
      "    self.write(text)\n",
      "UnicodeEncodeError: 'gbk' codec can't encode character '\\xa0' in position 14: illegal multibyte sequence\n",
      "Call stack:\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\pip.exe\\__main__.py\", line 7, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 79, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 234, in _main\n",
      "    return run(options, args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 180, in exc_logging_wrapper\n",
      "    status = run_func(*args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 45, in run\n",
      "    if not print_results(\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 162, in print_results\n",
      "    write_output(\"Location: %s\", dist.location)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\utils\\misc.py\", line 387, in write_output\n",
      "    logger.info(msg, *args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1477, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1624, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1634, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1696, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 968, in handle\n",
      "    self.emit(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Location: %s'\n",
      "Arguments: ('c:\\\\users\\\\zhouy\\\\appdata\\\\local\\\\programs\\\\python\\\\python310\\\\lib\\\\site-packages',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1672, in print\n",
      "    with self:\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 864, in __exit__\n",
      "    self._exit_buffer()\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 822, in _exit_buffer\n",
      "    self._check_buffer()\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 2027, in _check_buffer\n",
      "    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\_windows_renderer.py\", line 19, in legacy_windows_render\n",
      "    term.write_text(text)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\_win32_console.py\", line 403, in write_text\n",
      "    self.write(text)\n",
      "UnicodeEncodeError: 'gbk' codec can't encode character '\\xa0' in position 14: illegal multibyte sequence\n",
      "Call stack:\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\pip.exe\\__main__.py\", line 7, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 79, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 234, in _main\n",
      "    return run(options, args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 180, in exc_logging_wrapper\n",
      "    status = run_func(*args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 45, in run\n",
      "    if not print_results(\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 167, in print_results\n",
      "    write_output(\"Requires: %s\", \", \".join(dist.requires))\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\utils\\misc.py\", line 387, in write_output\n",
      "    logger.info(msg, *args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1477, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1624, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1634, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1696, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 968, in handle\n",
      "    self.emit(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Requires: %s'\n",
      "Arguments: ('',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1672, in print\n",
      "    with self:\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 864, in __exit__\n",
      "    self._exit_buffer()\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 822, in _exit_buffer\n",
      "    self._check_buffer()\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 2027, in _check_buffer\n",
      "    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\_windows_renderer.py\", line 19, in legacy_windows_render\n",
      "    term.write_text(text)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_vendor\\rich\\_win32_console.py\", line 403, in write_text\n",
      "    self.write(text)\n",
      "UnicodeEncodeError: 'gbk' codec can't encode character '\\xa0' in position 14: illegal multibyte sequence\n",
      "Call stack:\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\pip.exe\\__main__.py\", line 7, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 79, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 234, in _main\n",
      "    return run(options, args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 180, in exc_logging_wrapper\n",
      "    status = run_func(*args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 45, in run\n",
      "    if not print_results(\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 168, in print_results\n",
      "    write_output(\"Required-by: %s\", \", \".join(dist.required_by))\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\utils\\misc.py\", line 387, in write_output\n",
      "    logger.info(msg, *args)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1477, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1624, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1634, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 1696, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\logging\\__init__.py\", line 968, in handle\n",
      "    self.emit(record)\n",
      "  File \"C:\\Users\\zhouy\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Required-by: %s'\n",
      "Arguments: ('',)\n"
     ]
    }
   ],
   "source": [
    "!pip show pytube"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "a77f29b2-10e4-4c88-9197-7aebeebd7aaa",
   "metadata": {},
   "outputs": [],
   "source": [
    "from pytube import YouTube"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "970718bc-22ef-4ce2-80a8-8e732299bb6a",
   "metadata": {},
   "outputs": [],
   "source": [
    "output_path = '../resources/videos/'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "1923ad36-5c91-410c-958d-c60ccd28af74",
   "metadata": {},
   "outputs": [],
   "source": [
    "yt = YouTube('https://www.youtube.com/watch?v=SC9JgsM2rgQ&list=PL1JLWArGK6Z2zyBUGsdlU8lCxLrsxwFF2&index=279')\n",
    "yt = YouTube('https://www.youtube.com/watch?v=3Ma38nXugD0')\n",
    "yt = YouTube('https://www.youtube.com/watch?v=1hHtF54UmQU')\n",
    "yt = YouTube('https://www.youtube.com/watch?v=LFB680_JXCU')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "91258531-98d7-4dd6-9bc7-9f20661c9da5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'C:\\\\Users\\\\zhouy\\\\source\\\\repos\\\\GameScriptLib\\\\src\\\\app\\\\epic7\\\\tools\\\\../resources/videos/Epic Seven - Once In A Blue Moon - RTA 274.mp4'"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first().download(output_path=output_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c110138f-8a8f-4304-b42c-d37b90553135",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
